name: receptomagnet.com
favicon: null
layout_spectrum: 0.34304053522646427
typography_spectrum: 0.09287626761943102
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4501516332384199
  lightness: 0.2216840391047299
  saturation: 0.008608202217146754
  rhythmicContrast: 0.22640683175995946
purpose: []
